require('__lazy-bastards-friend__.prototypes.styles')

data:extend({
    {
        type = 'custom-input',
        name = 'lbf-toggle',
        key_sequence = 'CONTROL + SHIFT + L',
        action = 'lua',
    },
    {
        type = 'custom-input',
        name = 'lbf-toggle-exclude',
        key_sequence = '',
        action = 'lua',
    },
    {
        type = 'shortcut',
        name = 'lbf-toggle',
        action = 'lua',
        toggleable = true,
        associated_control_input = 'lbf-toggle',
        icon = '__lazy-bastards-friend__/graphics/icons/lbf-black-64.png',
        icon_size = 64,
        small_icon = '__lazy-bastards-friend__/graphics/icons/lbf-black-64.png',
        small_icon_size = 64,
        order = 'l[lbf]',
    },
    -- GUI icon (mip strip generated by tools/make_mipmaps.py, base-game
    -- gui-icon convention: 32px + 2 mipmaps). White art — it sits on the
    -- blue open button in the relative GUI.
    {
        type = 'sprite',
        name = 'lbf-icon',
        filename = '__lazy-bastards-friend__/graphics/icons/lbf-white-mip.png',
        priority = 'extra-high-no-scale',
        size = 32,
        mipmap_count = 2,
        flags = { 'gui-icon' },
    },
    -- Wordmark banner atop the open relative panel. Authored at 2x and drawn
    -- at scale 0.5 so it stays crisp up to 200% GUI scale (no mip strip).
    {
        type = 'sprite',
        name = 'lbf-banner',
        filename = '__lazy-bastards-friend__/graphics/gui/lbf-banner.png',
        priority = 'extra-high-no-scale',
        width = 536,
        height = 180,
        scale = 0.5,
        flags = { 'gui' },
    },
    -- Inline warning glyph for tooltip lines (relative.lua's flag_tooltip/
    -- shape_tooltip), replacing [img=virtual-signal.signal-alert]. Scaled to
    -- the same effective 16px as family_icons/flag_icons below, since it sits
    -- inline in text rather than as a button icon.
    {
        type = 'sprite',
        name = 'lbf-alert-warning',
        filename = '__core__/graphics/icons/alerts/warning-icon.png',
        size = 64,
        scale = 0.25,
        flags = { 'icon' },
    },
    -- Inline warning icon for the disabled-flag tooltips (relative.lua's
    -- flag_tooltip/shape_tooltip) — core's alert triangle rather than the
    -- virtual-signal sprite, scaled down to match the family/flag icons'
    -- effective 16px so it sits flush in a text line.
    {
        type = 'sprite',
        name = 'lbf-alert-warning',
        filename = '__core__/graphics/icons/alerts/warning-icon.png',
        size = 64,
        scale = 0.25,
        flags = { 'icon' },
    },
    -- Statistics-only item: the runtime pumps transferred
    -- counts into item production statistics under this name, so the mod's
    -- activity shows up in the vanilla production graphs (like base's 'science').
    {
        type = 'item',
        name = 'lbf-items-moved',
        icon = '__core__/graphics/icons/technology/constants/constant-logistic-slot.png',
        icon_size = 128,
        subgroup = 'other',
        order = 'zz[lbf-items-moved]',
        hidden_in_factoriopedia = true,
        stack_size = 1,
    },
})

-- Family icons prefixed onto mod-setting-name locale strings (settings.lua's
-- `order` groups settings by these same families) so the settings screen
-- shows at a glance which relative-GUI area each setting belongs to. Plain
-- standalone 'sprite' prototypes, referenced as [img=lbf-family-<x>] — the
-- singleton 'utility-sprites' prototype isn't extendable with arbitrary keys,
-- unlike ordinary sprites (github.com/RedRafe/speed-run-community's
-- prototypes/sprites.lua uses the same pattern).
-- 'behavior' isn't a settings-tree family — it's the relative-GUI Behavior
-- section title icon, a feed/collect mashup (see make_family_icons.py) since
-- that section covers both channels at once.
local family_icons = { 'feed', 'collect', 'appearance', 'watchdog', 'other', 'filters', 'behavior' }
for _, family in pairs(family_icons) do
    data:extend({
        {
            type = 'sprite',
            name = 'lbf-family-' .. family,
            filename = '__lazy-bastards-friend__/graphics/icons/family/lbf-family-' .. family .. '.png',
            size = 32,
            scale = 0.5,
            flags = { 'icon' },
        },
    })
end

-- Per-flag icons for the relative panel's Behavior/Appearance sprite-button
-- rows (tools/make_flag_icons.py). Separate from family_icons above: own
-- source directory, and each name here maps 1:1 to a settings-tree flag id
-- (or a plain preference like 'summary'), not a channel/family umbrella.
local flag_icons = {
    'fuel', 'ingredients', 'combat', 'trash', 'rebalance',
    'chests', 'ground', 'use-player-color', 'show-others', 'starvation', 'summary',
    'circle', 'square',
}
for _, flag in pairs(flag_icons) do
    data:extend({
        {
            type = 'sprite',
            name = 'lbf-flag-' .. flag,
            filename = '__lazy-bastards-friend__/graphics/icons/flags/lbf-flag-' .. flag .. '.png',
            size = 32,
            scale = 0.5,
            flags = { 'icon' },
        },
    })
end
