require('__lazy-bastards-friend__.prototypes.styles')

data:extend({
    {
        type = 'custom-input',
        name = 'lbf-toggle',
        key_sequence = 'CONTROL + SHIFT + L',
        action = 'lua',
    },
    {
        type = 'custom-input',
        name = 'lbf-toggle-exclude',
        key_sequence = '',
        action = 'lua',
    },
    {
        type = 'shortcut',
        name = 'lbf-toggle',
        action = 'lua',
        toggleable = true,
        associated_control_input = 'lbf-toggle',
        icon = '__lazy-bastards-friend__/graphics/icons/lbf-black-64.png',
        icon_size = 64,
        small_icon = '__lazy-bastards-friend__/graphics/icons/lbf-black-64.png',
        small_icon_size = 64,
        order = 'l[lbf]',
    },
    -- GUI icon (mip strip generated by tools/make_mipmaps.py, base-game
    -- gui-icon convention: 32px + 2 mipmaps). White art — it sits on the
    -- blue open button in the relative GUI.
    {
        type = 'sprite',
        name = 'lbf-icon',
        filename = '__lazy-bastards-friend__/graphics/icons/lbf-white-mip.png',
        priority = 'extra-high-no-scale',
        size = 32,
        mipmap_count = 2,
        flags = { 'gui-icon' },
    },
    -- Wordmark banner atop the open relative panel. Authored at 2x and drawn
    -- at scale 0.5 so it stays crisp up to 200% GUI scale (no mip strip).
    {
        type = 'sprite',
        name = 'lbf-banner',
        filename = '__lazy-bastards-friend__/graphics/gui/lbf-banner.png',
        priority = 'extra-high-no-scale',
        width = 536,
        height = 180,
        scale = 0.5,
        flags = { 'gui' },
    },
    -- Inline warning glyph for tooltip lines (relative.lua's flag_tooltip/
    -- shape_tooltip), replacing [img=virtual-signal.signal-alert]. Scaled to
    -- the same effective 16px as family_icons/flag_icons below, since it sits
    -- inline in text rather than as a button icon.
    {
        type = 'sprite',
        name = 'lbf-alert-warning',
        filename = '__core__/graphics/icons/alerts/warning-icon.png',
        size = 64,
        scale = 0.25,
        flags = { 'icon' },
    },
    -- Statistics-only item: the runtime pumps transferred
    -- counts into item production statistics under this name, so the mod's
    -- activity shows up in the vanilla production graphs (like base's 'science').
    {
        type = 'item',
        name = 'lbf-items-moved',
        icon = '__core__/graphics/icons/technology/constants/constant-logistic-slot.png',
        icon_size = 128,
        subgroup = 'other',
        order = 'zz[lbf-items-moved]',
        hidden_in_factoriopedia = true,
        stack_size = 1,
    },
})

-- Family icons prefixed onto mod-setting-name locale strings (settings.lua's
-- `order` groups settings by these same families) so the settings screen
-- shows at a glance which relative-GUI area each setting belongs to. Plain
-- standalone 'sprite' prototypes, referenced as [img=lbf-family-<x>] — the
-- singleton 'utility-sprites' prototype isn't extendable with arbitrary keys,
-- unlike ordinary sprites (github.com/RedRafe/speed-run-community's
-- prototypes/sprites.lua uses the same pattern).
-- 'behavior' isn't a settings-tree family — it's the relative-GUI Behavior
-- section title icon, a feed/collect mashup (see make_family_icons.py) since
-- that section covers both channels at once.
local family_icons = { 'feed', 'collect', 'appearance', 'watchdog', 'other', 'filters', 'behavior' }
for _, family in pairs(family_icons) do
    data:extend({
        {
            type = 'sprite',
            name = 'lbf-family-' .. family,
            filename = '__lazy-bastards-friend__/graphics/icons/family/lbf-family-' .. family .. '.png',
            size = 32,
            scale = 0.5,
            flags = { 'icon' },
        },
    })
end

-- Per-flag icons for the relative panel's Behavior/Appearance sprite-button
-- rows (tools/make_flag_icons.py). Separate from family_icons above: own
-- source directory, and each name here is a sprite suffix, independent of the
-- settings-tree flag id it's used for (relative.lua's FLAG_SPRITE_SUFFIX maps
-- id -> suffix; several ids share a shorter suffix than their id, e.g.
-- 'appearance_summary' -> 'summary').
local flag_icons = {
    'use-player-color', 'show-others', 'starvation', 'summary',
    'circle', 'square',
}
for _, flag in pairs(flag_icons) do
    data:extend({
        {
            type = 'sprite',
            name = 'lbf-flag-' .. flag,
            filename = '__lazy-bastards-friend__/graphics/icons/flags/lbf-flag-' .. flag .. '.png',
            size = 32,
            scale = 0.5,
            flags = { 'icon' },
        },
    })
end

-- Base/core vanilla icons reused for the flags below, referenced by full
-- filename (not `item.name`/`virtual-signal.name`) so a mod editing/removing
-- those prototypes can't break these sprites. Each entry mirrors its source
-- file's own mip-strip layout (base signal icons: 64px + 3 mip levels =
-- 120px wide; core's recipe-arrow: 32px + 1 mip level = 48px wide;
-- item-on-ground: flat 64px, no mip strip) and scales down to the same
-- effective 16px as the hand-drawn flag_icons above.
local vanilla_flag_icons = {
    fuel = { filename = '__base__/graphics/icons/signal/signal-fuel.png', size = 64, mipmap_count = 4, scale = 0.25 },
    ingredients = { filename = '__core__/graphics/icons/mip/recipe-arrow.png', size = 32, mipmap_count = 2, scale = 0.5 },
    combat = { filename = '__base__/graphics/icons/signal/signal-weapon.png', size = 64, mipmap_count = 4, scale = 0.25 },
    trash = { filename = '__base__/graphics/icons/signal/signal-trash-bin.png', size = 64, mipmap_count = 4, scale = 0.25 },
    rebalance = { filename = '__base__/graphics/icons/signal/signal-recycle.png', size = 64, mipmap_count = 4, scale = 0.25 },
    chests = { filename = '__base__/graphics/icons/signal/signal-stack-size.png', size = 64, mipmap_count = 4, scale = 0.25 },
    ground = { filename = '__core__/graphics/item-on-ground.png', size = 64, scale = 0.25 },
}
for flag, icon in pairs(vanilla_flag_icons) do
    data:extend({
        {
            type = 'sprite',
            name = 'lbf-flag-' .. flag,
            filename = icon.filename,
            size = icon.size,
            mipmap_count = icon.mipmap_count,
            scale = icon.scale,
            flags = { 'icon' },
        },
    })
end
