require('__lazy-bastards-friend__.prototypes.styles')

data:extend({
    {
        type = 'custom-input',
        name = 'lbf-toggle',
        key_sequence = 'CONTROL + SHIFT + L',
        action = 'lua',
    },
    {
        type = 'custom-input',
        name = 'lbf-toggle-exclude',
        key_sequence = '',
        action = 'lua',
    },
    {
        type = 'shortcut',
        name = 'lbf-toggle',
        action = 'lua',
        toggleable = true,
        associated_control_input = 'lbf-toggle',
        icon = '__lazy-bastards-friend__/graphics/icons/lbf-black-64.png',
        icon_size = 64,
        small_icon = '__lazy-bastards-friend__/graphics/icons/lbf-black-64.png',
        small_icon_size = 64,
        order = 'l[lbf]',
    },
    -- GUI icon (mip strip generated by tools/make_mipmaps.py, base-game
    -- gui-icon convention: 32px + 2 mipmaps). White art — it sits on the
    -- blue open button in the relative GUI.
    {
        type = 'sprite',
        name = 'lbf-icon',
        filename = '__lazy-bastards-friend__/graphics/icons/lbf-white-mip.png',
        priority = 'extra-high-no-scale',
        size = 32,
        mipmap_count = 2,
        flags = { 'gui-icon' },
    },
    -- Statistics-only item: the runtime pumps transferred
    -- counts into item production statistics under this name, so the mod's
    -- activity shows up in the vanilla production graphs (like base's 'science').
    {
        type = 'item',
        name = 'lbf-items-moved',
        icon = '__core__/graphics/icons/technology/constants/constant-logistic-slot.png',
        icon_size = 128,
        subgroup = 'other',
        order = 'zz[lbf-items-moved]',
        hidden_in_factoriopedia = true,
        stack_size = 1,
    },
})
