data:extend({
    -- Global runtime (map settings, admin-editable). Ordered by family to match the relative GUI's icon prefixes: watchdog, collect (behavior), appearance, then other/technical.
    {
        type = 'bool-setting',
        name = 'lbf-watchdog-enabled',
        setting_type = 'runtime-global',
        default_value = true,
        order = 'a[watchdog]-a',
    },
    {
        type = 'double-setting',
        name = 'lbf-spm-threshold',
        setting_type = 'runtime-global',
        default_value = 45,
        minimum_value = 0,
        order = 'a[watchdog]-b',
    },
    {
        type = 'bool-setting',
        name = 'lbf-allow-chest-collect',
        setting_type = 'runtime-global',
        default_value = true,
        order = 'b[collect]-a',
    },
    {
        type = 'int-setting',
        name = 'lbf-min-radius',
        setting_type = 'runtime-global',
        default_value = 4,
        minimum_value = 1,
        maximum_value = 100,
        order = 'c[appearance]-a',
    },
    {
        type = 'int-setting',
        name = 'lbf-max-radius',
        setting_type = 'runtime-global',
        default_value = 32,
        minimum_value = 1,
        maximum_value = 100,
        order = 'c[appearance]-b',
    },
    {
        type = 'int-setting',
        name = 'lbf-update-period',
        setting_type = 'runtime-global',
        default_value = 60,
        minimum_value = 6,
        maximum_value = 600,
        hidden = true,
        order = 'd[other]-a',
    },
    -- Per-player runtime. Ordered to match the relative GUI top-to-bottom: master switch, then Behavior (Feed, then Collect), then Appearance (radius through show-starvation/summary).
    {
        type = 'bool-setting',
        name = 'lbf-enabled',
        setting_type = 'runtime-per-user',
        default_value = true,
        order = 'a[other]-a',
    },
    {
        type = 'bool-setting',
        name = 'lbf-feed-fuel',
        setting_type = 'runtime-per-user',
        default_value = true,
        order = 'b[feed]-a',
    },
    {
        type = 'bool-setting',
        name = 'lbf-feed-ingredients',
        setting_type = 'runtime-per-user',
        default_value = true,
        order = 'b[feed]-b',
    },
    {
        type = 'bool-setting',
        name = 'lbf-feed-combat',
        setting_type = 'runtime-per-user',
        default_value = true,
        order = 'b[feed]-c',
    },
    {
        type = 'bool-setting',
        name = 'lbf-feed-trash',
        setting_type = 'runtime-per-user',
        default_value = false,
        order = 'b[feed]-d',
    },
    {
        type = 'bool-setting',
        name = 'lbf-feed-rebalance',
        setting_type = 'runtime-per-user',
        default_value = true,
        order = 'b[feed]-e',
    },
    {
        type = 'bool-setting',
        name = 'lbf-collect-chests',
        setting_type = 'runtime-per-user',
        default_value = false,
        order = 'c[collect]-a',
    },
    {
        type = 'bool-setting',
        name = 'lbf-collect-ground',
        setting_type = 'runtime-per-user',
        default_value = false,
        order = 'c[collect]-b',
    },
    {
        type = 'int-setting',
        name = 'lbf-radius',
        setting_type = 'runtime-per-user',
        default_value = 16,
        minimum_value = 1,
        maximum_value = 100,
        order = 'd[appearance]-a',
    },
    {
        type = 'string-setting',
        name = 'lbf-shape',
        setting_type = 'runtime-per-user',
        default_value = 'circle',
        allowed_values = { 'circle', 'square' },
        order = 'd[appearance]-b',
    },
    {
        type = 'bool-setting',
        name = 'lbf-fill-area',
        setting_type = 'runtime-per-user',
        default_value = true,
        order = 'd[appearance]-c',
    },
    {
        type = 'int-setting',
        name = 'lbf-opacity',
        setting_type = 'runtime-per-user',
        default_value = 8,
        minimum_value = 0,
        maximum_value = 100,
        order = 'd[appearance]-d',
    },
    {
        type = 'bool-setting',
        name = 'lbf-use-my-color',
        setting_type = 'runtime-per-user',
        default_value = true,
        order = 'd[appearance]-e',
    },
    {
        type = 'color-setting',
        name = 'lbf-color',
        setting_type = 'runtime-per-user',
        default_value = { r = 1, g = 0.5, b = 0, a = 1 },
        order = 'd[appearance]-f',
    },
    {
        type = 'bool-setting',
        name = 'lbf-show-others-area',
        setting_type = 'runtime-per-user',
        default_value = false,
        order = 'd[appearance]-g',
    },
    {
        type = 'bool-setting',
        name = 'lbf-show-starvation',
        setting_type = 'runtime-per-user',
        default_value = false,
        order = 'd[appearance]-h',
    },
    {
        type = 'bool-setting',
        name = 'lbf-show-summary',
        setting_type = 'runtime-per-user',
        default_value = false,
        order = 'd[appearance]-i',
    },
})
