data:extend({
    -- Global runtime (map settings, admin-editable)
    {
        type = 'bool-setting',
        name = 'lbf-watchdog-enabled',
        setting_type = 'runtime-global',
        default_value = true,
        order = 'a[watchdog]-a',
    },
    {
        type = 'double-setting',
        name = 'lbf-spm-threshold',
        setting_type = 'runtime-global',
        default_value = 45,
        minimum_value = 0,
        order = 'a[watchdog]-b',
    },
    {
        type = 'bool-setting',
        name = 'lbf-watchdog-stops-combat',
        setting_type = 'runtime-global',
        default_value = false,
        order = 'a[watchdog]-c',
    },
    {
        type = 'int-setting',
        name = 'lbf-min-radius',
        setting_type = 'runtime-global',
        default_value = 4,
        minimum_value = 1,
        maximum_value = 100,
        order = 'b[radius]-a',
    },
    {
        type = 'int-setting',
        name = 'lbf-max-radius',
        setting_type = 'runtime-global',
        default_value = 32,
        minimum_value = 1,
        maximum_value = 100,
        order = 'b[radius]-b',
    },
    {
        type = 'int-setting',
        name = 'lbf-update-period',
        setting_type = 'runtime-global',
        default_value = 60,
        minimum_value = 6,
        maximum_value = 600,
        hidden = true,
        order = 'c[perf]-a',
    },
    {
        type = 'bool-setting',
        name = 'lbf-allow-chest-take',
        setting_type = 'runtime-global',
        default_value = true,
        order = 'd[chests]-a',
    },
    -- Per-player runtime
    {
        type = 'int-setting',
        name = 'lbf-radius',
        setting_type = 'runtime-per-user',
        default_value = 16,
        minimum_value = 1,
        maximum_value = 100,
        order = 'a',
    },
})
