data:extend({
    -- Global runtime (map settings, admin-editable)
    {
        type = 'bool-setting',
        name = 'lbf-watchdog-enabled',
        setting_type = 'runtime-global',
        default_value = true,
        order = 'a[watchdog]-a',
    },
    {
        type = 'double-setting',
        name = 'lbf-spm-threshold',
        setting_type = 'runtime-global',
        default_value = 45,
        minimum_value = 0,
        order = 'a[watchdog]-b',
    },
    {
        type = 'bool-setting',
        name = 'lbf-watchdog-stops-combat',
        setting_type = 'runtime-global',
        default_value = false,
        order = 'a[watchdog]-c',
    },
    {
        type = 'int-setting',
        name = 'lbf-min-radius',
        setting_type = 'runtime-global',
        default_value = 4,
        minimum_value = 1,
        maximum_value = 100,
        order = 'b[radius]-a',
    },
    {
        type = 'int-setting',
        name = 'lbf-max-radius',
        setting_type = 'runtime-global',
        default_value = 32,
        minimum_value = 1,
        maximum_value = 100,
        order = 'b[radius]-b',
    },
    {
        type = 'int-setting',
        name = 'lbf-update-period',
        setting_type = 'runtime-global',
        default_value = 60,
        minimum_value = 6,
        maximum_value = 600,
        hidden = true,
        order = 'c[perf]-a',
    },
    {
        type = 'bool-setting',
        name = 'lbf-allow-chest-take',
        setting_type = 'runtime-global',
        default_value = true,
        order = 'd[chests]-a',
    },
    -- Per-player runtime.
    {
        type = 'int-setting',
        name = 'lbf-radius',
        setting_type = 'runtime-per-user',
        default_value = 16,
        minimum_value = 1,
        maximum_value = 100,
        order = 'a',
    },
    {
        type = 'bool-setting',
        name = 'lbf-feed-fuel',
        setting_type = 'runtime-per-user',
        default_value = true,
        order = 'b',
    },
    {
        type = 'bool-setting',
        name = 'lbf-feed-ingredients',
        setting_type = 'runtime-per-user',
        default_value = true,
        order = 'c',
    },
    {
        type = 'bool-setting',
        name = 'lbf-take-chests',
        setting_type = 'runtime-per-user',
        default_value = false,
        order = 'd',
    },
    {
        type = 'bool-setting',
        name = 'lbf-pickup-ground',
        setting_type = 'runtime-per-user',
        default_value = false,
        order = 'e',
    },
    {
        type = 'bool-setting',
        name = 'lbf-drain-trash',
        setting_type = 'runtime-per-user',
        default_value = false,
        order = 'f',
    },
    {
        type = 'bool-setting',
        name = 'lbf-show-summary',
        setting_type = 'runtime-per-user',
        default_value = false,
        order = 'g',
    },
    {
        type = 'string-setting',
        name = 'lbf-shape',
        setting_type = 'runtime-per-user',
        default_value = 'circle',
        allowed_values = { 'circle', 'square' },
        order = 'h',
    },
    {
        type = 'bool-setting',
        name = 'lbf-fill-area',
        setting_type = 'runtime-per-user',
        default_value = true,
        order = 'i',
    },
    {
        type = 'int-setting',
        name = 'lbf-opacity',
        setting_type = 'runtime-per-user',
        default_value = 8,
        minimum_value = 2,
        maximum_value = 50,
        order = 'j',
    },
    {
        type = 'bool-setting',
        name = 'lbf-use-my-color',
        setting_type = 'runtime-per-user',
        default_value = true,
        order = 'k',
    },
    {
        type = 'color-setting',
        name = 'lbf-color',
        setting_type = 'runtime-per-user',
        default_value = { r = 1, g = 0.5, b = 0, a = 1 },
        order = 'l',
    },
    {
        type = 'bool-setting',
        name = 'lbf-show-to-others',
        setting_type = 'runtime-per-user',
        default_value = false,
        order = 'm',
    },
})
